services:
  - type: web
    name: estateiq-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
